version: '3'
services:
  appy-hour-python:
    image: ddoxton/appy-hour
    container_name: appy-hour-python
    command: python appy_hour.py
    build:
      dockerfile: Dockerfile.dev
      context: ./appy_hour
    volumes:
      - appy-hour-vol:/app
    networks:
      - appy-hour-net
    ports:
      - '5000:5000'
  appy-hour-react:
    image: ddoxton/appy-react
    container_name: appy-hour-react
    command: npm run start
    build:
      dockerfile: Dockerfile.dev
      context: ./appy-hour-react
    ports:
      - '3000:3000'
    depends_on:
      - appy-hour-python
    networks:
      - appy-hour-net
    environment: 
      - REACT_APP_API_URL=http://appy-hour-python:3000
      
volumes:
  appy-hour-vol:
networks:
  appy-hour-net:
    external: true